project_id = "djnysigashxtjfhxpzyj"

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.process-recurring-tasks]
verify_jwt = false
